version: '3'

services:
  # -- Django container --
  app:
    # vars are injected at runtime, so no need to specify env_var value here.
    image: 'postgres/15-bullseye'

    volumes:
      - ..:/workspace:delegated

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  # -- PostgreSQL container --
  db:
    env_file: .env_db # var created at build-time, so we need an env_file
    image: 'postgres/15-bullseye'
    restart: unless-stopped

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
